BEGIN
    ; CREATE TABLE IF NOT EXISTS USERS ( USER_ID TEXT PRIMARY KEY, PASSWORD TEXT NOT NULL );
    CREATE TABLE IF NOT EXISTS TODOS ( TODO_ID SERIAL PRIMARY KEY, USER_ID TEXT REFERENCES USERS ON DELETE CASCADE, TITLE TEXT NOT NULL, STATUS TEXT CONSTRAINT CHECK_STATUS CHECK ( STATUS IN ( 'Unprocessed', 'Proceeding', 'Finished' ) ), DETAILS TEXT NOT NULL DEFAULT '' );
    COMMIT;
